name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.0.4

      - name: check persista
        run: |
          python -c "import persista"

      - name: check persista.agents
        run: |
          python -c "from persista import store"

      - name: check persista.utils
        run: |
          python -c "from persista import utils"
          python -c "from persista.utils import imports"
